version: "3.8"

services:
  api:
    build:
      context: ./API-PO-REDES/RestAPI/Docker
      dockerfile: Dockerfile
    ports:
      - "8443:80"
  webgl:
    build:
      context: ./deploy/chessui
      dockerfile: Dockerfile
    ports:
      - "443:80"
    depends_on:
      - api
  gcontroller:
    build:
      context: ./GameController
      dockerfile: Dockerfile
    ports:
      - "6666:80"
    depends_on:
      - api
